### PR TITLE
Addition of #string_placeholder in Chapel tmbundle to resolve issue #6899 for the incorrect syntax highlighting of escape character

### PR DESCRIPTION
**Pull request by victor-ludorum**
@lydia-duncan  In the previous PR #11  I have added **#string_escaped_char**  in the chapel tmbundle to resolve the issue ****Incorrect Syntax Highlighting For Escaped Character** '\"' **#6899** . Here comes the addition of **#string_placeholder** and it's description .
Kindly review the changes done

### CODE REVIEW

**Comment by victor-ludorum** [comment]
@lydia-duncan  As you have suggested it is made as a separate branch from the previous branch**(newbranch4)** so that changes can be reflected separately .

**Comment by lydia-duncan** [comment]
I have verified that this combination of changes works

**Comment by victor-ludorum** [comment]
Oh. that's nice @lydia-duncan 😊

**Comment by victor-ludorum** [comment]
Thanks mam @lydia-duncan 😊 !!

**Pull request merged**
